### ISSUE TITLE
UUID in machinekit.ini is always the same

### ISSUE THREAD

**Issue by ArcEye** [machinekit/machinekit-hal#113]
<a href="https://github.com/machinekoder"><img src="https://avatars3.githubusercontent.com/u/1467368?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [machinekoder](https://github.com/machinekoder)**
_Fri Mar 13 13:00:36 2015_
_Originally opened as https://github.com/machinekit/machinekit/issues/531_

----

The Machinekit Debian packages feature a default machinekit.ini file. There is an UUID values in this configuration file that is relevant to identify different Machinekit instances on the network. This UUID should be autogenerated after package install to ensure a different identification for every machine.

**Comment by ArcEye** [comment]
See https://github.com/machinekit/machinekit-cnc/issues/39 for full text, this is a copy header only.

**Comment by cerna** [comment]
This should be resolved in machinekit/machinekit#1447 and as such in Machinekit-HAL codebase.
