### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ArcEye** [machinekit/machinekit-hal#114]
<a href="https://github.com/RunningLight"><img src="https://avatars1.githubusercontent.com/u/1719026?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [RunningLight](https://github.com/RunningLight)**
_Thu Apr 16 22:16:44 2015_
_Originally opened as https://github.com/machinekit/machinekit/issues/563_

----

This isn't a "sky is falling" issue for now, but we have about 300 python files in our source repo and many are inconsistent with Python 3. Some conflicts can be resolved with minor syntactic changes, e.g., to modify the argument lists of old-style print statements; some require actual thought.

Why do I mention this, especially since I still write Python the way I learned it before the turn of the century? Because I was just reading a posting by a Debian team member (re)confirming their commitment to eliminate Python 2 from Debian by 2020.  Five years isn't such a long time that we shouldn't be thinking about this problem now. 

At a minimum, I believe we should commit to support both Python 2 and 3 in any new modules we write and to begin to port the modules we already have. We might even build pylint or something like it into our code testing.

To quote from https://docs.python.org/3/howto/pyporting.html

> A key point about supporting Python 2 & 3 simultaneously is that you can start today! Even if your dependencies are not supporting Python 3 yet that does not mean you can’t modernize your code now to support Python 3. Most changes required to support Python 3 lead to cleaner code using newer practices even in Python 2.
> 
> Another key point is that modernizing your Python 2 code to also support Python 3 is largely automated for you. While you might have to make some API decisions thanks to Python 3 clarifying text data versus binary data, the lower-level work is now mostly done for you and thus can at least benefit from the automated changes immediately.

Several automation tools which aid in porting and testing are mentioned in the above-referenced page.

**Comment by ArcEye** [comment]
Changes were made to make the invocation of python, specify `python2`, therefore allowing distros which ship with default of python3 to build without issue.

Python 3 being non backwardly compatible with python 2 was a spectacular own goal which python.org have yet to recover from.

A lot of elements in python 3 have been back ported to python 2.7, but until all major libs are re-written in python specific form, this situation will continue.

**Comment by machinekoder** [comment]
It's time to re-open this issue. Python 2.7 EOL is quickly approaching. Most major libraries already dropped Python 2 support and so should we too. Python2->3 conversion is not very hard in general when it comes to Python files. However, it might harder to porth the few Python 2 CPython extensions we have.

Here is the Python 2.7 death clock: https://pythonclock.org/

**Comment by ArcEye** [comment]
Not sure that the code we have in python will be the main problem.

This is the list of dependent python libraries as best as I can determine.
How many of these libraries are available in python 3 or can be used with it?
```
libboost-python-dev
cython (>= 0.19) (appears so)
dh-python
python-tk
python-zmq (>= 14.0.1)
python-setuptools,
python-simplejson
python-imaging or python-pil
python-imaging-tk or python-pil.imagetk
python-gnome2
python-glade2
python-numpy 
python-gtksourceview2
python-vte
python-xlib
python-gtkglext1
python-configobj,
python-protobuf (>= 2.4.1)
python-avahi
python-pyftpdlib
python-pydot
python-gst0.10 or python-gst-1.0 
python-netifaces
```

**Comment by loganpowell** [comment]
Just cross-referencing this with the folks in LinuxCNC, who are also having this conversation:

https://github.com/LinuxCNC/linuxcnc/issues/403#issuecomment-452896732

Also, if you're having problems with Cython, apparently there's a new kid on the block, which doesn't require the special syntax of Cython code: https://github.com/Nuitka/Nuitka

Also this: http://python-future.org/automatic_conversion.html
[source](https://docs.python.org/3/howto/pyporting.html)

**Comment by ArcEye** [comment]
Thanks for the link.

We suffer from the linuxcnc python / gtk legacy and eventually it will all start to unravel. ;)

**Comment by machinekoder** [comment]
If we could skip the UI libs, it would be a lot less work. I have looked into making the Axis and co code PEP8 compatible once and noticed that there is quite a lot of old-style Python code in there. With old-style, I mean syntax that isn't available in Python 3 anymore and already deprecated in newer Python 2 versions.

An auto-converter might be a good start. I encourage to do a complete QA cleanup of the Python code at the same time. Implementing automatic flake8 tests and auto-formatting with black. I've already applied those tools to everything Machinetalk related and the `lib/python/machinekit` libs.

Somewhat harder might be the CPython stuff and also the embedded Python support in HAL and interp. We will have to take a look at that.

I don't see why Cython should make problems. It's frequently used project in the Python3 world as well.

**Comment by ebo** [comment]
has there been any forward motion on this in the last year and a half?  I mean not only is python2 EOL'ed, many OS's are no longer supporting it.  This is already an issue, and will eventually be a real problem.

Also, with the advent of numba, it might make replacing the cython code a lot easier.

**Comment by ebo** [comment]
Also, let me know if anyone has already started a branch/fork for this and I will look at adding to it...

**Comment by zultron** [comment]
I don't think there's been any real, recent effort here towards python3 compatibility.  I did start to look at this a week or so back and [wrote a few commits][1] before dropping it to return to the LCNC-EMC on MK-HAL port; see #267.  I'm expecting to have a working branch in the next week or so.

Given that, python3 compatibility will be done for HAL in this project, and separately for EMC over in the LCNC project.

On the LCNC side, they have an [issue open][2] that cites several good attempts.  @rene-dev already has a branch working (congratulations, wow!).

On the MK-HAL side, we can certainly port a lot of that work over.  My naive and woefully incomplete attempt is probably mostly already done in the LCNC effort, but it still may have changes only applicable to MK, like the changes to `comp`/`instcomp`, protobuf and packaging.

[1]:  https://github.com/zultron/machinekit-hal/commits/2020-04-24-python3
[2]: https://github.com/LinuxCNC/linuxcnc/issues/403

**Comment by zultron** [comment]
Also, for Debian folks, see comments over at #268 related to python3 and the port to Bullseye where py3 has been dropped (I remember @ebo runs Gentoo or another non-Debian-derivative distro).

- https://github.com/machinekit/machinekit-hal/issues/268#issuecomment-618985239
- https://github.com/machinekit/machinekit-hal/issues/268#issuecomment-619079983
- https://github.com/machinekit/machinekit-hal/issues/268#issuecomment-619154041

**Comment by rene-dev** [comment]
linuxcnc master now supports python3, all tests pass, and axis works.

**Comment by zultron** [comment]
> linuxcnc master now supports python3, all tests pass, and axis works.

@rene-dev You're awesome!  And the other folks that contributed to that effort!

Are you targeting the 2.8 release, or saving it for 2.9?

**Comment by rene-dev** [comment]
That’s the target for 2.9(2.8 is close to release), because no other ui components work due to gtk2 problems with python3. Im currently porting everything to gtk3, and the qt people need to get qt working with python3, which should be less of an issue.

**Comment by ebo** [comment]
Since my intent is to build both a Gentoo overlay, and actual up to date plug and pray images for RPi 3//4 (using gentoo and buster based), I've redone the old linuxcnc and machinekit ebuilds.  I've also started new ones for linuxcnc-2.8.* and gave up on machinekit-hal at the moment.  I can pick that back up later once it is actually working.  It has been a couple of days since I got the ebuilds marginally working, so I cannot give you a current status because the base OS.  Unfortunately I do not have equipment to test while in isolation.  @zultron, please ping me when you do release the python3 related changes and I will try to break away enough time to give it a serious poke.  Until then I'm in the middle of rebuilding the traction battery in my Prius and other non-trivial household projects + plus passing my master gardeners cert...

**Comment by zultron** [comment]
The changes to support building LCNC-EMC against MK-HAL are now in master, so if you'd like to try this, be my guest.

I wrote some quick notes pointing to the modified LCNC branch and how to build it [here][1].

To take advantage of what @rene-dev has done, you'll have to merge the LCNC `master` branch into that branch.  You'll have to muddle through a few conflicts, unfortunately.

Then, as I said above, take a look at [my previous attempt][2] and LinuxCNC/linuxcnc#403 to start the HAL-side work.  I bet you could get 80% done in a day or two.

[1]: https://github.com/machinekit/machinekit-hal/issues/267#issuecomment-626515589
[2]: https://github.com/zultron/machinekit-hal/commits/2020-04-24-python3

**Comment by ebo** [comment]
I will look into this ASAP -- but as I am working 40+hrs/week, it will 
only be in the evenings...

As a note, before reading this I was thinking of asking if there had 
been any progress.  I must be psychic ;-)

Anyway, I will let you know how it goes.  My intent is to get it first 
building on my Gentoo laptop (running a preempt kernel), and then on a 
RPi (both under Gentoo and Buster).

   More later,

   EBo --

**Comment by ebo** [comment]
I was asked to move a note from https://github.com/machinekit/machinekit-hal/issues/267#issuecomment-627676909 regarding build issues I am having with building machinekit-hal.  I have been building off of 2020-04-24-python3.  Please inform me if there is a better one to use.

Since my ebuild is "live" meaning that it checks the repository and updates if any changes have been made, I am getting a different set of error messages at the moment.  In the future I will plan on providing full build logs.  I also need to go to work, so I will have to work on this later.

**Comment by ebo** [comment]
ok... I just made a clean fork, and started working on the 2020-04-24-python3 branch.

the commit https://github.com/ebo/machinekit-hal/commit/5e483b0669ac8c1d83517ece66f54ff8e9672130 fixes a couple of issues with autoconfig.  You may or may not consider this enough for a proper PR, but it is a start. 

Also, using my portage ebuild script it currently generates a build configuration of "./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/machinekit-hal-9999 --htmldir=/usr/share/doc/machinekit-hal-9999/html --libdir=/usr/lib64 --enable-drivers --with-x --with-python=/usr/bin/python3.7 --with-boost-python=boost_python-3.7 --with-libmodbus"

Do you see any issues with the config so far?  I can easily prune it, but I would like to know if anyone sees an issue.

**Comment by zultron** [comment]
@ebo  I'm sorry, let me clarify my above https://github.com/machinekit/machinekit-hal/issues/114#issuecomment-626518484 .  Please start with latest `machinekit-hal` repo's `master` branch, since major changes have been added just in the last week.

After that, take at look at LinuxCNC/linuxcnc#403, where they discuss doing the same thing at the LCNC project, and just finished.  Some of the most challenging changes will be in recent PRs.  My [2020-04-24-python3 branch][1] may contain useful things to pick, but it's really just a few hours head start that still hasn't been rebased onto the latest `master` branch.

[1]: https://github.com/zultron/machinekit-hal/commits/2020-04-24-python3

**Comment by ebo** [comment]
Using the above setup I get the following error:

Compiling ++ hal/lib/halmodule.cc
hal/lib/halmodule.cc: In function ‘void pyhal_delete(PyObject*)’:
hal/lib/halmodule.cc:156:11: error: ‘halobject’ {aka ‘struct halobject’} has no member named ‘ob_type’
  156 |     self->ob_type->tp_free(self);
      |           ^~~~~~~
hal/lib/halmodule.cc: In function ‘int pyhal_write_common(halitem*, PyObject*)’:
hal/lib/halmodule.cc:160:18: error: ‘PyInt_Check’ was not declared in this scope; did you mean ‘PySet_Check’?
  160 |     int is_int = PyInt_Check(value);
      |                  ^~~~~~~~~~~
      |                  PySet_Check
hal/lib/halmodule.cc:161:28: error: ‘PyInt_AsLong’ was not declared in this scope; did you mean ‘PyLong_AsLong’?
  161 |     long intval = is_int ? PyInt_AsLong(value) : -1;
      |                            ^~~~~~~~~~~~
      |                            PyLong_AsLong
hal/lib/halmodule.cc: In function ‘PyObject* pyhal_read_common(halitem*)’:
hal/lib/halmodule.cc:280:34: error: ‘PyInt_FromLong’ was not declared in this scope; did you mean ‘PyLong_FromLong’?
  280 |             case HAL_S32: return PyInt_FromLong(*(item->u->pin.s32));
      |                                  ^~~~~~~~~~~~~~
      |                                  PyLong_FromLong
hal/lib/halmodule.cc:291:34: error: ‘PyInt_FromLong’ was not declared in this scope; did you mean ‘PyLong_FromLong’?
  291 |             case HAL_S32: return PyInt_FromLong(item->u->param.s32);
      |                                  ^~~~~~~~~~~~~~
      |                                  PyLong_FromLong
hal/lib/halmodule.cc: In function ‘PyObject* pyhal_repr(PyObject*)’:
hal/lib/halmodule.cc:442:12: error: ‘PyString_FromFormat’ was not declared in this scope; did you mean ‘PyBytes_FromFormat’?
  442 |     return PyString_FromFormat("<hal component %s(%d) with %d pins and params>",
      |            ^~~~~~~~~~~~~~~~~~~
      |            PyBytes_FromFormat
hal/lib/halmodule.cc: In function ‘PyObject* pyhal_getattro(PyObject*, PyObject*)’:
hal/lib/halmodule.cc:455:46: error: ‘PyString_AsString’ was not declared in this scope
  455 |     return pyhal_read_common(find_item(self, PyString_AsString(attro)));
      |                                              ^~~~~~~~~~~~~~~~~
...

I need to call it a night soon.  Any insights welcomed.

**Comment by ebo** [comment]
Ahhh... sorry about that.  I will pull run live from master, and take a look at LCNC#403.

That said, the fixes to the configure.ac might be useful.  I seem to remember a similar issue before, so maybe this will help.

**Comment by zultron** [comment]
> ok... I just made a clean fork, and started working on the 2020-04-24-python3 branch.

Messages crossing in flight!  See above:  I recommend starting with `master` branch to avoid later merge headaches.

> the commit [ebo@5e483b0](https://github.com/ebo/machinekit-hal/commit/5e483b0669ac8c1d83517ece66f54ff8e9672130) fixes a couple of issues with autoconfig. You may or may not consider this enough for a proper PR, but it is a start.

Those changes look fine to me.

> Also, using my portage ebuild script it currently generates a build configuration of "./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/machinekit-hal-9999 --htmldir=/usr/share/doc/machinekit-hal-9999/html --libdir=/usr/lib64 --enable-drivers --with-x --with-python=/usr/bin/python3.7 --with-boost-python=boost_python-3.7 --with-libmodbus"
>
> Do you see any issues with the config so far? I can easily prune it, but I would like to know if anyone sees an issue.

That looks reasonable.  While developing, why not start with an "RIP" build?

**Comment by zultron** [comment]
> Using the above setup I get the following error:
> 
> Compiling ++ hal/lib/halmodule.cc
> hal/lib/halmodule.cc: In function ‘void pyhal_delete(PyObject*)’:
> hal/lib/halmodule.cc:156:11: error: ‘halobject’ {aka ‘struct halobject’} has no member named ‘ob_type’
> 156 | self->ob_type->tp_free(self);
> | ^~~~~~~
>  [...]

This is where I recommend you start looking at the changes that went into LCNC.  This is the most challenging part of the port for me, at least, but fortunately @strufkin and maybe others have already done this for us.

**Comment by ebo** [comment]
On May 13 2020 8:26 PM, John Morris wrote:
>> ok... I just made a clean fork, and started working on the 
>> 2020-04-24-python3 branch.
>
> Messages crossing in flight!  See above:  I recommend starting with
> `master` branch to avoid later merge headaches.
>
>> the commit 
>> [ebo@5e483b0](https://github.com/ebo/machinekit-hal/commit/5e483b0669ac8c1d83517ece66f54ff8e9672130) 
>> fixes a couple of issues with autoconfig. You may or may not consider 
>> this enough for a proper PR, but it is a start.
>
> Those changes look fine to me.

Take a look at my master branch.  I had to make changes to the same two 
lines...

>> Also, using my portage ebuild script it currently generates a build 
>> configuration of "./configure --prefix=/usr 
>> --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu 
>> --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share 
>> --sysconfdir=/etc --localstatedir=/var/lib 
>> --docdir=/usr/share/doc/machinekit-hal-9999 
>> --htmldir=/usr/share/doc/machinekit-hal-9999/html --libdir=/usr/lib64 
>> --enable-drivers --with-x --with-python=/usr/bin/python3.7 
>> --with-boost-python=boost_python-3.7 --with-libmodbus"
>>
>> Do you see any issues with the config so far? I can easily prune it, 
>> but I would like to know if anyone sees an issue.
>
> That looks reasonable.  While developing, why not start with an "RIP" 
> build?

I though all of this was more stable than it is.  Normally I can start 
writing a gentoo ebuild out of the box and get it to do the right thing 
immediately and build the execs using standard Gentoo'isms.  Neither 
machinekit and linuxcnc are really ready for prime time again...

**Comment by rene-dev** [comment]
FYI, Im currently working on this, and will keep you updated.

**Comment by ebo** [comment]
On Aug 11 2020 3:50 AM, Rene Hopf wrote:
> FYI, Im currently working on this, and will keep you updated.

thanks.  I spent a little time and ended up giving up as it will be a 
bigger effort than I had time for AND I was not sure once it got working 
if I would end up with a fully working machine (which is what I really 
need -- ie. rebuild/replace the controllers for at least 2 machines if 
not 6).

**Comment by rene-dev** [comment]
https://github.com/machinekit/machinekit-hal/pull/299
please test.

**Comment by ebo** [comment]
On Aug 21 2020 12:47 PM, Rene Hopf wrote:
> https://github.com/machinekit/machinekit-hal/pull/299
> please test.

I will try to test it this weekend (still need to put in a few hours at 
work).

That said, many of the automated tests are failing at:

*  Build Machinekit-HAL Debian package for Stretch, <fill in the tag 
here>

Looking at the details

...
checking consistency of all components of python development 
environment... no
191 configure: error: in `/home/machinekit/build/machinekit-hal/src':
192 configure: error:
193   Could not link test program to Python. Maybe the main Python 
library has been
194  installed in some non-standard library path. If so, pass it to 
configure,
195  via the LIBS environment variable.
196  Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
197  
============================================================================
198   ERROR!
199   You probably have to install the development version of the 
Python package
200   for your distribution.  The exact name of this package varies 
among them.
201  
============================================================================

Not sure if it is a problem with the test not pulling python3-dev or 
something else...

   More later,

   EBo --

**Comment by rene-dev** [comment]
like I said in the PR, the code works with python2 and 3, but the build system does not.
A decision needs to be made:
Drop python2 (EOL 8 month ago, not available in new distros) and change CI to build with python3
Update build system for 2 and 3, and change CI so it builds for 2 and 3.
Linuxcnc decided on the 2nd option, as most UIs dont work with python3.

**Comment by ebo** [comment]
On Aug 21 2020 3:25 PM, Rene Hopf wrote:
> like I said in the PR, the code works with python2 and 3, but the
> build system does not.
> A decision needs to be made:
> Drop python2 (EOL 8 month ago, not available in new distros) and
> change CI to build with python3
> Update build system for 2 and 3, and change CI so it builds for 2 and 
> 3.
> Linuxcnc decided on the 2nd option, as most UIs dont work with 
> python3.

Ahhh... sorry I misunderstood.

My 2c would be to drop python2 support, and move on.  Keeping the 
legacy support at this point will only divide what little resources the 
community has.  I doubt that very many people who are still running 
python2-only systems are really wanting to upgrade machinekit.  I could 
be wrong, but wouldn't it be easier to update the base system to get the 
latest LCNC/MK?  I know that someone on the list will scream bloody 
murder -- if they do, they care enough that they should help to maintain 
p2.  As I said my 2c, but both LCNC and MK are effectively dysfunctional 
due to the bitrot. As mentioned, I will try to poke at this over the 
weekend.

**Comment by zultron** [comment]
Really happy to see this!  I'll spend some time with it tomorrow.

> A decision needs to be made:
> Drop python2 (EOL 8 month ago, not available in new distros) and change CI to build with python3

That's my vote, but...

> Update build system for 2 and 3, and change CI so it builds for 2 and 3.
> Linuxcnc decided on the 2nd option, as most UIs dont work with python3.

...This will break Machinekit's EMC application (a lightly modified port of LinuxCNC), too.  And that prevents EMC application users from upgrading their OS to Debian Bullseye and Ubuntu Focal.

Have you heard what the LCNC community is thinking about Python3 UI compatibility?

Do you know exactly which UIs are affected?

**Comment by rene-dev** [comment]
axis works, qt should be easy to port, its all the gtk2 stuff and gremlin that breaks. porting them to gtk3 is probably 80% done.
if EMC application gets updated to latest master, axis should just work.
LCNC community has not made a decision. my vote is dropping python2.

**Comment by cerna** [comment]
>...This will break Machinekit's EMC application (a lightly modified port of LinuxCNC), too. And that prevents EMC application users from upgrading their OS to Debian Bullseye and Ubuntu Focal[...]

Question is, should it be solved here? Respectively, cannot this problem be solved in (and as such isolated to) EMCApplication alone?

If the core functionality (_motion_, _task_, _iocontrol_, _NML_ and such) is happily working with Python3 and just some HMIs are problematic. Well, I would say: **Let it be**. For me, it is far more important that the currently actively developed ones, like _Probe Basic_, are functioning.

As I presented in #299, I would also assassinate the _Python 2_.

**Comment by cerna** [comment]
I have started looking at how to make #299 build and test in CI workflow and realized that the state is from before the build-system (Docker flow) was changed, so now I am doing some rebasing, dropping and history rewrite, cherry-picking from @zultron's focal branch. Basically, no development, only git magic.

Hopefully it will build.

**Comment by zultron** [comment]
On my side, I updated `debian/control` to pull in Python3 versions of deps, building on `amd64`/Stretch.

First error:
```
Compiling hal/cython/machinekit/hal.c
hal/cython/machinekit/hal.c: In function ‘__pyx_pf_10machinekit_3hal_10StreamRing_12read’:
hal/cython/machinekit/hal.c:23549:17: error: implicit declaration of function ‘PyString_FromStringAndSize’ [-Werror=implicit-function-declaration]
     __pyx_t_2 = PyString_FromStringAndSize(((char const *)(__pyx_v_v[0]).rv_base), (__pyx_v_v[0]).rv_len); if (unlikely(!__pyx_t_2)) __PYX_ERR(7, 233, __pyx_L1_error)
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
hal/cython/machinekit/hal.c:23549:15: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
     __pyx_t_2 = PyString_FromStringAndSize(((char const *)(__pyx_v_v[0]).rv_base), (__pyx_v_v[0]).rv_len); if (unlikely(!__pyx_t_2)) __PYX_ERR(7, 233, __pyx_L1_error)
               ^
hal/cython/machinekit/hal.c:23601:15: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
     __pyx_t_2 = PyString_FromStringAndSize(((char const *)(__pyx_v_v[1]).rv_base), (__pyx_v_v[1]).rv_len); if (unlikely(!__pyx_t_2)) __PYX_ERR(7, 238, __pyx_L1_error)
               ^
cc1: all warnings being treated as errors
```

Looks like `PyString_FromStringAndSize` doesn't exist in python3.  We can get it from the `py3c-dev` package that's not in Stretch, but is in more recent distros.

I'll investigate more tomorrow.

**Comment by cerna** [comment]
Source package `Avahi`, version 0.8.3, which includes the binary package `python3-avahi`, appears buildable on Debian Stretch, _amd64_. This looks promising.

BTW, I am putting all these packages to my [testing repository](https://cloudsmith.io/~cerna/repos/testing/packages/).

**Comment by zultron** [comment]
And I don't even start to understand yet about how to deal with the whole `/usr/bin/python{,2,3}` distinction and how the right version gets selected.  For one thing, the `yapps2` packages are build into `/usr/lib/python2.7`, but the first line of `/usr/bin/yapps` is `#!/usr/bin/python`.

This is one reason we can't `update-alternatives --install /usr/bin/python python /usr/bin/python3 1`.  Another reason, I tried that on Stretch, and immediately some Debian package pre/post scripts started breaking.

So this means we have to be explicit in our scripts about choosing `#!/usr/bin/python3`.

As for the Debian packaging, there's no `python3-avahi` package until Debian post-Bullseye and Ubuntu Groovy.

**Comment by zultron** [comment]
> Why confused? The whole Avahi package is build with all parts - so there are architecture specific parts, so I have to try building it per architecture in _QEMU_. Good thing it appears to also install.

That was supposed to be a frowny face, next to the happy face:  happy that you have the problem figured out (just as I was getting around to pointing it out!), but not happy that we seem to be returning to the days of Jessie when the Machinekit repos had to carry stacks of packages outside mainline distros in order to run.  That raises the hurdles for anyone building from source and anyone running an unsupported distro (including non-Debian).

That doesn't change my opinion the move to Python 3 needs to happen ASAP, since Python2 has been EOL for so many months now and has already been dropped in the newest distros.  And it needs to happen ASAP even if it means dropping Python 2 support.

It's painful, but there's no avoiding it, and we're making the best of a bad situation.

**Comment by zultron** [comment]
> Source package `Avahi`, version 0.8.3, which includes the binary package `python3-avahi`, appears buildable on Debian Stretch, _amd64_. This looks promising.

@cerna While you're at it, could you pull in the `yapps2` package from sid?  It builds fine in Stretch without changes.

https://packages.debian.org/source/sid/yapps2

**Comment by zultron** [comment]
>  I updated `debian/control` to pull in Python3 versions of deps

> Looks like `PyString_FromStringAndSize` doesn't exist in python3.

Submitted at https://github.com/rene-dev/machinekit-hal/pull/1

**Comment by cerna** [comment]
@zultron,
>@cerna While you're at it, could you pull in the yapps2 package from sid? It builds fine in Stretch without changes.

`Python3-yapps` is in the [cerna/testing](https://cloudsmith.io/~cerna/repos/testing/packages/detail/deb/python3-yapps/2.2.1-3.1/d=debian%252Fstretch;xp=1/) repository. I guess - to allow merging the rene-dev/machinekit-hal#1, I should transfer it to machinekit/machinekit?

In that repo is also the [`py3c-dev`](https://cloudsmith.io/~cerna/repos/testing/packages/detail/deb/py3c-dev/1.0-1/d=debian%252Fstretch;xp=1/)(_all_ type of package) and `Avahi*` packages (for _amd64_, _armhf_, _arm64_ and _i386_). All for Debian Stretch.

I probably should build the `Avahi*` for Debian Buster too.

**Comment by zultron** [comment]
> `Python3-yapps` is in the [cerna/testing](https://cloudsmith.io/~cerna/repos/testing/packages/detail/deb/python3-yapps/2.2.1-3.1/d=debian%252Fstretch;xp=1/) repository. I guess - to allow merging the [rene-dev#1](https://github.com/rene-dev/machinekit-hal/pull/1), I should transfer it to machinekit/machinekit?

Excellent!  Yes please!

> In that repo is also the [`py3c-dev`](https://cloudsmith.io/~cerna/repos/testing/packages/detail/deb/py3c-dev/1.0-1/d=debian%252Fstretch;xp=1/)(_all_ type of package) and `Avahi*` packages (for _amd64_, _armhf_, _arm64_ and _i386_). All for Debian Stretch.

Even better!

> I probably should build the `Avahi*` for Debian Buster too.

Yes.  This package will plague us until Bullseye and Focal are EOL.

@cerna Thanks for all the support on this.

**Comment by ebo** [comment]
I started playing with this late last night.  I got stuck with the error:

checking python module: google.protobuf.descriptor... Traceback (most recent call last):
...
configure: error: failed to find required module google.protobuf.descriptor

I've tried 4 different versions of protobuf on Gentoo (including a live build from github), and I could not get any of them to work.

I have comments on a report that just came in on Friday (due in 1 week), and some things for work.  I will have to bow out of the testing for now.  If someone has a quick fix I will give it another go, but my time at the moment is limited to an hour or two and not full days.

**Comment by cerna** [comment]
@zultron,
`python3-yapps`, `yapps2` and `py3c-dev` for Stretch are all in [machinekit/machinekit](https://cloudsmith.io/~machinekit/repos/machinekit/packages/) repository. I tried to build the versions on par with Buster - so the version in Stretch is not higher than the officially available from Debian repositories for Buster.

I am currently uploading the `Avahi*` packages. That will take a while.

**Comment by zultron** [comment]
@ebo,
> checking python module: google.protobuf.descriptor... Traceback (most recent call last):
> ...
> configure: error: failed to find required module google.protobuf.descriptor

Have you configured for `python3`?  Try these:
```
python3 -c 'import google.protobuf.descriptor'
python -c 'import google.protobuf.descriptor'
```

I hit this error before discovering the `./configure --with-python=python3` option.

**Comment by ebo** [comment]
@zultron, thanks for pointing out -with-python=python3.  I had forgotten about that. Once I add that, and run "python3 -c 'import google.protobuf.descriptor'" and "python -c 'import google.protobuf.descriptor'".  the -c 'import google.protobuf.descriptor' still produces the error.

**Comment by zultron** [comment]
> @zultron, thanks for pointing out -with-python=python3. I had forgotten about that. Once I add that, and run "python3 -c 'import google.protobuf.descriptor'" and "python -c 'import google.protobuf.descriptor'". the -c 'import google.protobuf.descriptor' still produces the error.

The two `python* -c` commands are just a sanity check, not needed for the build.

Do they both fail?  If the `python3` version fails, your `./configure --with-python=python3` command will also fail.

**Comment by ebo** [comment]
I get that.  I should have said that I tried both python3 and python '-c ...',  after installing 3 different versions of protobuf (version 3.11.4, 3.12.2, and github master).  I've also modified the comand for python3 and python2 to make sure that I am trying both.

**Comment by cerna** [comment]
All `Avahi*` packages for Debian Stretch and Debian Buster are successfully uploaded to the [machinekit/machinekit](https://cloudsmith.io/~machinekit/repos/machinekit/packages/) repository.

Looking at the Ubuntu, the `py3c-dev` package is in all versions, `python3-yapps` is missing from Ubuntu Bionic 18.04 LTS and the `Avahi*` are missing both from Ubuntu Bionic 18.04 LTS and Ubuntu Focal 20.04 LTS.

So, I am going to take the version from Groovy and build them.

(The dependency's repository is attacking 350 packages. It would be a good idea to create a static backup and upload it to Mega or something else which is long-term stable.)

---

And when I try the [zultron:pr-299-rebase rebased](https://github.com/cerna/machinekit-hal/commits/pr-299-rebase) I get the package build [OK](https://github.com/cerna/machinekit-hal/runs/1018789908) output - the error is on testing.

The download at the machinekit/machinekit dependency's repository is up. So at least packages are working.

**Comment by rene-dev** [comment]
> This is one reason we can't `update-alternatives --install /usr/bin/python python /usr/bin/python3 1`. Another reason, I tried that on Stretch, and immediately some Debian package pre/post scripts started breaking.

I also strongly advise against using update-alternatives with python, it can break the system, and its really the job of the build system to pick the right versions.

**Comment by zultron** [comment]
> I also strongly advise against using update-alternatives with python, it can break the system, and its really the job of the build system to pick the right versions.

Point taken!  It broke Stretch quite badly.  As I said in #299, my [rebased branch][1] fixes all the shebangs to `python3`.

I haven't tried to bake in @cerna's `py3c-dev` packages yet.  The packaging does make use of the rest of the new Yapps and Avahi packages.

[1]: https://github.com/zultron/machinekit-hal/tree/pr-299-rebase/

**Comment by ebo** [comment]
On Aug 23 2020 1:49 PM, John Morris wrote:
>> I also strongly advise against using update-alternatives with 
>> python, it can break the system, and its really the job of the build 
>> system to pick the right versions.
>
> Point taken!  It broke Stretch quite badly.  As I said in #299, my
> [rebased branch][1] fixes all the shebangs to `python3`.
>
> I haven't tried to bake in @cerna's `py3c-dev` packages yet.  The
> packaging does make use of the rest of the new Yapps and Avahi
> packages.
>
> [1]: https://github.com/zultron/machinekit-hal/tree/pr-299-rebase/

on a totally unrelated not I received a post on converting python code 
to an Abstract Syntax Tree and back again.  Stackoverflow has an 
interesting reply to this:

https://docs.python.org/2/library/2to3.html

and it got me to thinking about this is SUCH a pain, I wonder if anyone 
wrote a converter...  Well check this out -- python's 2to3:

     https://docs.python.org/2/library/2to3.html

I had not known about this...  Never used it, so do not know how much 
3'isms it will deal with, but it is likely a start with hundreds of 
python files...

**Comment by zultron** [comment]
> python's 2to3

I did know about `2to3`, and yet for some reason I still went with emacs macros.  That might've turned the 30 minute job into one minute.  It was about a hundred files.  Sometimes I choose the known pain, even if it's likely going to be worse.

**Comment by ebo** [comment]
On Aug 23 2020 2:34 PM, John Morris wrote:
> ...
> Sometimes I choose the known pain,
> even if it's likely going to be worse.

Fair enough.

**Comment by cerna** [comment]
Missing packages for Ubuntu Bionic 18.04 LTS and Ubuntu Focal 20.04 LTS uploaded to the [Machinekit/Machinekit](https://cloudsmith.io/~machinekit/repos/machinekit/) dependency's repository.

**Comment by rene-dev** [comment]
closed by https://github.com/machinekit/machinekit-hal/pull/303
