### ISSUE TITLE
information when machinekit fails is wrong/inadequate

### ISSUE THREAD

**Issue by ArcEye** [machinekit/machinekit-hal#119]
<a href="https://github.com/luminize"><img src="https://avatars1.githubusercontent.com/u/2206842?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [luminize](https://github.com/luminize)**
_Wed Apr  4 06:53:44 2018_
_Originally opened as https://github.com/machinekit/machinekit/issues/1366_

----

When something fails the following is shown:

```
See /var/log/linuxcnc.log for more information.
Shutting down and cleaning up Machinekit...
Cleanup done
Machinekit terminated with an error.  You can find more information in the log:
   /home/machinekit/linuxcnc_debug.txt
and
   /home/machinekit/linuxcnc_print.txt
as well as in the output of the shell command 'dmesg' and in the terminal
```

Personally I think this is wrong info and should contain better instructions, like something as "start with export DEBUG=5" and "look at /var/log/linuxcnc.log before posting". Maybe some basic instructions in helping people narrowing down.

I don't remember ever finding anything in linuxcnc_debux.txt or linuxcnc_print.txt

Opinions?

**Comment by ArcEye** [comment]
See https://github.com/machinekit/machinekit-cnc/issues/44 for full details, this is a header only.

**Comment by luminize** [comment]
The machinekit-hal package does not contain the "machinekit" script at scripts/linuxcnc.in so this issue has no meaning here.
Following these PR's https://github.com/machinekit/machinekit-cnc/pull/54 and https://github.com/machinekit/machinekit/pull/1416 this issue can be closed
