### ISSUE TITLE
Build is littered with compiler warnings

### ISSUE THREAD

**Issue by ArcEye** [machinekit/machinekit-hal#120]
<a href="https://github.com/zultron"><img src="https://avatars1.githubusercontent.com/u/1940736?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zultron](https://github.com/zultron)**
_Fri Apr  6 23:20:12 2018_
_Originally opened as https://github.com/machinekit/machinekit/issues/1368_

----

The build is littered with compiler warnings.  When compiling my updates, this makes it really hard to tell if I've introduced a new warning.  #327 had them all fixed a couple of years back, but that was never merged, and it's unclear how many of those patches still address outstanding warnings, or how many would even apply.

**Comment by ArcEye** [comment]
See https://github.com/machinekit/machinekit-cnc/issues/45 for full details, this is a copy header only

**Comment by zultron** [comment]
Can this issue be closed now that the corresponding machinekit/machinekit-cnc#45 is fixed?
