### ISSUE TITLE
mb2hal is missing from machinekit-hal

### ISSUE THREAD

**Issue by ArcEye** [machinekit/machinekit-hal#168]
At present, although #166 fixes the new library API problem, mb2hal is not in machinekit-hal

mb2hal requires headers that are part of machinekit-cnc to build
As these cannot exist in both repos, need to look at it later to work out best build strategy.

**Comment by cerna** [comment]
The pull request machinekit/machinekit-hal#258 added the MB2HAL component back into Machinekit-HAL code proper. Given the fact that Machinekit-HAL has priority over Machinekit-CNC and there was request for this component on the Google Groups, this needs to be solved from Machinekit-CNC end.
