### ISSUE TITLE
jplan writes to input pin when enable low and not in ringbuffer mode

### ISSUE THREAD

**Issue by zultron** [machinekit/machinekit-hal#169]
[This line][1] caused me some serious confusion.  I'm not sure the right way to deal with this yet.

[1]:  https://github.com/machinekit/machinekit-hal/blob/master/src/hal/jplanner/jplan.c#L101

**Comment by zultron** [comment]
Fixed link, oops!

**Comment by zultron** [comment]
If I'm understanding this comp correctly (I'm weak on the MK ring buffer implementation), near the beginning of `instantiate_jplan()`, whether `hal_ring_attachf()` succeeds or fails determines whether the instance is in `queued` mode with cmd coming through a ringbuffer (and copied to output pin `pos_cmd`), or in not-`queued` mode with cmd coming in through `pos_cmd`, input pin since 8cb9aa70.

Line 101, which sets `pos_cmd` to `curr_pos` when enable is low, looks like it was fine until commit 8cb9aa70, when to support cmd coming from a signal in not-`queued` ringbuffer mode, `pos_cmd` was turned from an IO pin into an input pin.  @luminize 

Although some application designers may want to artificially set cmd to fb when enable is low to prevent movement when enable goes high, it should really be up to the application to handle this problem externally wrt. the `jplan` comp.  IMO, line 101 should just be removed.

If there really is a valid use case, after commit 8cb9aa70, it only applies to ringbuffer configurations.  Configurations will produce poor results where cmd input comes from a signal connected to the `pos_cmd` input pin but not from a ringbuffer:

- When enable is low this scheme produces the unexpected results I found where the signal attached to the `pos_cmd` input pin mysteriously changes (and the output pin connected to the signal has an inconsistent value)
- When enable goes high this scheme causes motion anyway since the pin resumes being updated with the signal's value

If truly necessary, the workaround to preserve the ringbuffer use case should be to set `pos_cmd` to feedback conditionally only `if (queued)`, when the pin is an output pin and command comes from the ringbuffer.

**Comment by luminize** [comment]
I'm not sure I understand the problem.
the line you mention `*(joint->pos_cmd) = *(joint->curr_pos);`  does not take any feedback value at all but it holds the `*(joint->pos_cmd)` value (also a pin) to the latest (internally) calculated value  `*(joint->curr_pos)` which coincidentally is also an output pin (but not any feedback).

Since pins are read, and the values dereferenced and passed to the `update_joint()` function  https://github.com/machinekit/machinekit-hal/blob/master/src/hal/jplanner/jplan.c#L177-L184
I don't see why the line 101 is the reason of the strange behaviour you describe.
Having said that, when looking thru the code, it might be a redundant action.

Have you tried commenting out line 101 and see if a `non-queued` jplan instance keeps working?

I don't understand what changing pins from `HAL_IO` to `HAL_IN` has to do with this.
https://github.com/machinekit/machinekit-hal/commit/8cb9aa70352bd5c9567762f7ab4fb6c53e4724ca

**Comment by zultron** [comment]
@luminize `pos_cmd` is a `HAL_IN` pin (see lines 237, 238) when there's no ringbuffer attached (lines 210-220).  Writing to an input pin (line 101) inside a comp writes the attached signal's value, and thus any `HAL_OUT` pin setting the signal's value from another comp.  Of course, input pins should only be read from, not written to.  (Did I make this up?)

I'm sorry, "feedback" was the wrong word; you can replace "cmd" and "fb" with "input" or "`pos_cmd`" and "output" or "`curr_pos`".

Does that simplify the problem's explanation, and show how 8cb9aa7 is related?

**Comment by luminize** [comment]
> @luminize pos_cmd is a HAL_IN pin (see lines 237, 238) when there's no ringbuffer attached (lines 210-220). Writing to an input pin (line 101) inside a comp writes the attached signal's value, and thus any HAL_OUT pin setting the signal's value from another comp. Of course, input pins should only be read from, not written to. (Did I make this up?)

You're 100% right here. This should not be done.
This means that the writing to the input pin should not happen, or that we introduce an instance variable which we can modify (if we want/need to)
The Q is if we indeed need to set a `local pos-cmd` to `curr-vel` value.

> I'm sorry, "feedback" was the wrong word; you can replace "cmd" and "fb" with "input" or "pos_cmd" and "output" or "curr_pos".
>  Does that simplify the problem's explanation, and show how 8cb9aa7 is **related?**

I'm afraid don't see the relation to 8cb9aa7 . For any use in configurations, not having a `HAL_IN` or `HAL_OUT` pin is ugly to work with, hence I changed the `HAL_IO` to `HAL_IN`. But I fail to see what it has to do with line 101.
Unless you mean that having `pos-cmd` as HAL_IO pin means you are allowed to change `pos-cmd` from inside the comp (is there a sefaty net to not change the `out` pin of another component???)

**Comment by zultron** [comment]
> The Q is if we indeed need to set a `local pos-cmd` to `curr-vel` value.

Yep.  My recommendations for both 'yes' and 'no' answers are in https://github.com/machinekit/machinekit-hal/issues/169#issuecomment-451827018.  The authors of the comp should decide whether there's a valid use case for doing that, or whether `pos_cmd` should be managed outside the comp.

> I'm afraid don't see the relation to [8cb9aa7](https://github.com/machinekit/machinekit-hal/commit/8cb9aa70352bd5c9567762f7ab4fb6c53e4724ca) . For any use in configurations, not having a `HAL_IN` or `HAL_OUT` pin is ugly to work with, hence I changed the `HAL_IO` to `HAL_IN`. But I fail to see what it has to do with line 101.
> Unless you mean that having `pos-cmd` as HAL_IO pin means you are allowed to change `pos-cmd` from inside the comp (is there a sefaty net to not change the `out` pin of another component???)

Yes, IO pins may be legally changed.  8cb9aa7 allowed signals to be attached, but didn't address the issue of writing to `pos_cmd`.  IMO, if jplan is to be used without ringbuffers, attaching a signal to cmd input is a good thing (+1 for 8cb9aa7); IMO, writing to `pos_cmd` or artificially setting cmd input to cmd output shouldn't be done (-1 for line 101).  Others may have a different perspective.

**Comment by luminize** [comment]
I'm afraid it is not up to the original author(s) but to the person solving this issue.

- writing to the `HAL_IN` pin `pos-cmd` in `non-queued` is not allowed IMO.
- `pos-cmd` should not be an `HAL_IO` pin

so my take would be to remove the offending line 101.
