### ISSUE TITLE
Update iocontrol with stuff patched for triac_toolchanger 

### ISSUE THREAD

**Issue by alkabal** [machinekit/machinekit-hal#174]
Hi

I have found a special version of iocontrol with 2 added stuff work done by ArcEye 2012/2011
porting from linuxcnc to machinekit version is a 5 minute job, i have try compile and test with success i can do a pull request if you agree

the add on is 

    // NEW pins to generate auto update of tool number at startup when using
    // ArcEye's Triac toolchanger component
    hal_s32_t *currenttool; /* input to set current tool at start up */
    hal_bit_t *update;	   /* flag to update tool number to currenttool */
    // the following pins are needed for toolchanging

This make possible to have a better control with a modern toolchanger.

To ArcEye's I think unfortunately know your opinion about me but I have really good progress in my project.

Of course I can now easily compile it myself but it seems to me that the update would not pose a problem of compatibility and that these are really missing functions.

The iocontrol_v2 protocol has very little interest

Br
[ioControl.zip](https://github.com/machinekit/machinekit-hal/files/2752656/ioControl.zip)

**Comment by ArcEye** [comment]
> I have found a special version of iocontrol with 2 added stuff work done by ArcEye 2012/2011

If you hadn't been such a pain, I might have told you :laughing: 

> i can do a pull request if you agree

Do I want you to submit my work in a PR, tempting but no thanks

There is a later version with a pin to set the number of tools instead of being hard coded and initialised as a pin for debugging.

https://github.com/machinekit/machinekit/pull/1446 refers
