### ISSUE TITLE
Regression causes parse failure in HAL files

### ISSUE THREAD

**Issue by mbuesch** [machinekit/machinekit-hal#217]
700de8b562cf12484fc9e3440876c0b8aba0aa7f introduces a regression for parsing of hal files with lines longer than 200 characters.
Such line lengths are easily reachable, e.g. if lots of loadrt parameters are used.
The parser will truncate the line at 200 chars.

Why did this change go from MAX_CMD_LEN (1024) to CMD_BUF_LEN (200)?
I suggest we go back to MAX_CMD_LEN in all places where CMD_BUF_LEN is used.

**Comment by ArcEye** [comment]
I can't remember exactly now.  

The usage of MAX_CMD_LEN was only introduced in https://github.com/machinekit/machinekit-hal/commit/187f851f61d7cf7da4b7eaa89efddfa67910df12, it had previously been a fixed buffer of 200 bytes.

When https://github.com/machinekit/machinekit-hal/commit/187f851f61d7cf7da4b7eaa89efddfa67910df12 threw errors, I think I reverted the changes until it worked again and that got left at 200.

The whole thing was an example of why you should not run something like coverity on code that works and then try to `fix the errors`.  Think someone got bored :stuck_out_tongue_closed_eyes: 

As soon as you start using gcc 7 and 8, you will get a huge number of potential buffer overrun / truncation warnings from the legacy C code in particular.
This largely comes from using the same size defines for buffers and any copy from one to the other has potential to overrun or be incomplete (truncated), even if given the data involved and size of the buffer, in reality it will never happen.
It is a product of the coding style and may be difficult to root out.

PR submitted for this change.
